new

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -1,162 +1,220 @@
 #!/sbin/sh
+# Magisk Module Update Binary
+# Optimized for zRAM Manager
+
+###################
+# Initialization
+###################
 
 TMPDIR=/dev/tmp
 MOUNTPATH=/dev/magisk_img
 
-# Default permissions
+# Set default permissions
 umask 022
 
 # Initial cleanup
-rm -rf $TMPDIR 2>/dev/null
-mkdir -p $TMPDIR
+rm -rf "$TMPDIR" 2>/dev/null
+mkdir -p "$TMPDIR"
 
-# echo before loading util_functions
-ui_print() { echo "$1"; }
+###################
+# Functions
+###################
 
+# UI print function (before util_functions loaded)
+ui_print() {
+    echo "$1"
+}
+
+# Check if Magisk version is too old
 require_new_magisk() {
-  ui_print "***********************************"
-  ui_print " Please install the latest Magisk! "
-  ui_print "***********************************"
-  exit 1
+    ui_print "***********************************"
+    ui_print " Please install latest Magisk!     "
+    ui_print " Minimum required: 15.3            "
+    ui_print "***********************************"
+    exit 1
 }
 
+# Check if using imageless Magisk (v19+)
 imageless_magisk() {
-  [ $MAGISK_VER_CODE -gt 18100 ]
-  return $?
+    [ "$MAGISK_VER_CODE" -gt 18100 ]
+    return $?
 }
 
-##########################################################################################
-# Environment
-##########################################################################################
+# Abort with cleanup
+abort() {
+    ui_print "$1"
+    cleanup
+    exit 1
+}
+
+# Cleanup function
+cleanup() {
+    cd /
+    imageless_magisk || unmount_magisk_img 2>/dev/null
+    $BOOTMODE || recovery_cleanup
+    rm -rf "$TMPDIR" "$MOUNTPATH" 2>/dev/null
+}
+
+###################
+# Environment Setup
+###################
 
 OUTFD=$2
 ZIPFILE=$3
 
-mount /data 2>/dev/null
+# Mount /data
+mount /data 2>/dev/null || abort "! Cannot mount /data"
 
-# Load utility functions
+# Load Magisk utility functions
 if [ -f /data/adb/magisk/util_functions.sh ]; then
-  . /data/adb/magisk/util_functions.sh
-  NVBASE=/data/adb
+    . /data/adb/magisk/util_functions.sh
+    NVBASE=/data/adb
 elif [ -f /data/magisk/util_functions.sh ]; then
-  require_new_magisk
+    require_new_magisk
 else
-  UF=$TMPDIR/common/unityfiles
-  unzip -oq "$ZIPFILE" 'common/unityfiles/util_functions.sh' -d $TMPDIR >&2
-  [ -f "$UF/util_functions.sh" ] || { ui_print "! Unable to extract zip file !"; exit 1; }
-  . $UF/util_functions.sh
+    # Extract util_functions from ZIP
+    UF=$TMPDIR/common/unityfiles
+    unzip -oq "$ZIPFILE" 'common/unityfiles/util_functions.sh' -d "$TMPDIR" >&2
+    
+    [ -f "$UF/util_functions.sh" ] || abort "! Unable to extract ZIP file"
+    . "$UF/util_functions.sh"
 fi
 
-# Preperation for flashable zips
+###################
+# Preparation
+###################
+
+# Setup flashable environment
 setup_flashable
 
 # Mount partitions
 mount_partitions
 
-# Detect version and architecture
+# Detect API level and architecture
 api_level_arch_detect
 
 # Setup busybox and binaries
 $BOOTMODE && boot_actions || recovery_actions
 
-##########################################################################################
-# Preparation
-##########################################################################################
+###################
+# Extract Files
+###################
 
-# Extract common files
-unzip -oj "$ZIPFILE" module.prop install.sh uninstall.sh 'common/*' -d $TMPDIR >&2
+ui_print "- Extracting module files..."
 
-[ ! -f $TMPDIR/install.sh ] && abort "! Unable to extract zip file!"
+# Extract essential files
+unzip -oq "$ZIPFILE" \
+    module.prop \
+    install.sh \
+    uninstall.sh \
+    'common/*' \
+    'addon/*' \
+    -d "$TMPDIR" >&2
+
+[ -f "$TMPDIR/install.sh" ] || abort "! Unable to extract install.sh"
+
 # Load install script
-. $TMPDIR/install.sh
+. "$TMPDIR/install.sh"
 
+###################
+# Module Setup
+###################
+
+# Determine module paths
 if $MAGISK; then
-  if imageless_magisk; then
-    $BOOTMODE && MODDIRNAME=modules_update || MODDIRNAME=modules
-    MODULEROOT=$NVBASE/$MODDIRNAME
-  else
-    $BOOTMODE && IMGNAME=magisk_merge.img || IMGNAME=magisk.img
-    IMG=$NVBASE/$IMGNAME
-    request_zip_size_check "$ZIPFILE"
-    mount_magisk_img
-    MODULEROOT=$MOUNTPATH
-  fi
+    if imageless_magisk; then
+        $BOOTMODE && MODDIRNAME=modules_update || MODDIRNAME=modules
+        MODULEROOT=$NVBASE/$MODDIRNAME
+    else
+        $BOOTMODE && IMGNAME=magisk_merge.img || IMGNAME=magisk.img
+        IMG=$NVBASE/$IMGNAME
+        request_zip_size_check "$ZIPFILE"
+        mount_magisk_img
+        MODULEROOT=$MOUNTPATH
+    fi
 else
-  MODULEROOT=$MOUNTPATH
+    MODULEROOT=$MOUNTPATH
 fi
 
-MODID=`grep_prop id $TMPDIR/module.prop`
+# Get module ID and set module path
+MODID=$(grep_prop id "$TMPDIR/module.prop")
 MODPATH=$MODULEROOT/$MODID
 
+# Display module information
 print_modname
 
-# Anything after this point won't run
-
+ui_print " "
 ui_print "******************************"
-ui_print "Powered by Magisk (@topjohnwu)"
+ui_print "  Powered by Magisk          "
+ui_print "  by topjohnwu               "
 ui_print "******************************"
+ui_print " "
 
-##########################################################################################
-# Install
-##########################################################################################
+###################
+# Installation
+###################
 
-# Create mod paths
-rm -rf $MODPATH 2>/dev/null
-mkdir -p $MODPATH
+ui_print "- Installing module..."
 
+# Create module directory
+rm -rf "$MODPATH" 2>/dev/null
+mkdir -p "$MODPATH"
+
+# Run installation
 on_install
 
-# Remove placeholder
-rm -f $MODPATH/system/placeholder 2>/dev/null
+# Clean up placeholder files
+rm -f "$MODPATH/system/placeholder" 2>/dev/null
 
-# Custom uninstaller
-[ -f $TMPDIR/uninstall.sh ] && cp -af $TMPDIR/uninstall.sh $MODPATH/uninstall.sh
+# Copy custom uninstaller
+[ -f "$TMPDIR/uninstall.sh" ] && cp -af "$TMPDIR/uninstall.sh" "$MODPATH/uninstall.sh"
 
-# Auto Mount
+# Handle auto-mount
 if imageless_magisk; then
-  $SKIPMOUNT && touch $MODPATH/skip_mount
+    $SKIPMOUNT && touch "$MODPATH/skip_mount"
 else
-  $SKIPMOUNT || touch $MODPATH/auto_mount
+    $SKIPMOUNT || touch "$MODPATH/auto_mount"
 fi
 
-# prop files
-$PROPFILE && cp -af $TMPDIR/system.prop $MODPATH/system.prop
+# Copy prop files
+$PROPFILE && cp -af "$TMPDIR/system.prop" "$MODPATH/system.prop"
 
-# Module info
-cp -af $TMPDIR/module.prop $MODPATH/module.prop
+# Copy module.prop
+cp -af "$TMPDIR/module.prop" "$MODPATH/module.prop"
+
+# Update module info for Magisk Manager
 if $BOOTMODE; then
-  # Update info for Magisk Manager
-  if imageless_magisk; then
-    mktouch $NVBASE/modules/$MODID/update
-    cp -af $TMPDIR/module.prop $NVBASE/modules/$MODID/module.prop
-  else
-    mktouch /sbin/.magisk/img/$MODID/update
-    cp -af $TMPDIR/module.prop /sbin/.magisk/img/$MODID/module.prop
-  fi
+    if imageless_magisk; then
+        mktouch "$NVBASE/modules/$MODID/update"
+        cp -af "$TMPDIR/module.prop" "$NVBASE/modules/$MODID/module.prop"
+    else
+        mktouch "/sbin/.magisk/img/$MODID/update"
+        cp -af "$TMPDIR/module.prop" "/sbin/.magisk/img/$MODID/module.prop"
+    fi
 fi
 
-# post-fs-data mode scripts
-$POSTFSDATA && cp -af $TMPDIR/post-fs-data.sh $MODPATH/post-fs-data.sh
-
-# service mode scripts
-$LATESTARTSERVICE && cp -af $TMPDIR/service.sh $MODPATH/service.sh
+# Copy boot scripts
+$POSTFSDATA && cp -af "$TMPDIR/post-fs-data.sh" "$MODPATH/post-fs-data.sh"
+$LATESTARTSERVICE && cp -af "$TMPDIR/service.sh" "$MODPATH/service.sh"
 
 # Handle replace folders
 for TARGET in $REPLACE; do
-  mktouch $MODPATH$TARGET/.replace
+    mktouch "$MODPATH$TARGET/.replace"
 done
 
-ui_print "- Setting permissions"
+###################
+# Finalization
+###################
+
+ui_print "- Setting permissions..."
 set_permissions
 
-##########################################################################################
-# Finalizing
-##########################################################################################
+ui_print "- Cleaning up..."
+cleanup
 
-cd /
-imageless_magisk || unmount_magisk_img
-$BOOTMODE || recovery_cleanup
-rm -rf $TMPDIR $MOUNTPATH
+ui_print " "
+ui_print "- Installation complete!"
+ui_print "- Please reboot to apply changes"
+ui_print " "
 
-ui_print "- Done"
 exit 0
